### ISSUE TITLE
Please update Erlang.mk

### ISSUE THREAD

**Issue by essen** [jj1bdx/sfmt-erlang#19]
Hello,

I recently made a backward incompatible change in Erlang.mk and your project is basically the only one that is concerned. The C_SRC_OUTPUT variable doesn't need the extension anymore (need to remove the ".so") because on Windows it must be ".dll" so Erlang.mk now defines it separately and sets it automatically.

Any chance you can update Erlang.mk and do this small change? Would be appreciated. I can probably send a PR tomorrow otherwise.

**Comment by jj1bdx** [comment]
@essen Thx for letting me know. It's done in https://github.com/jj1bdx/sfmt-erlang/commit/42fe343cd3017287172bfe81956427e7bb32fd40 - I think this will do. Please let me know it it doesn't work.

**Comment by jj1bdx** [comment]
Note that I've updated the master branch and the tag is 0.11.0 now.

**Comment by jj1bdx** [comment]
If you have successfully built sfmt on Windows, please do let me know; that will be a very good news.

**Comment by essen** [comment]
Thanks! Works as intended.

And I can confirm that *yes*, sfmt does build and load on Windows.

```
Eshell V7.0  (abort with ^G)
1> sfmt:uniform().
0.8009796260858373
2> os:type().
{win32,nt}
```

**Comment by jj1bdx** [comment]
@essen :+1: Well done! > sfmt:uniform/0 on Windows
