### ISSUE TITLE
Failed to load NIF

### ISSUE THREAD

**Issue by timCF** [jj1bdx/sfmt-erlang#22]
Use commit 83076a3 , gives me warning on compile

```
15:22:28.370 [warn]  The on_load function for module sfmt returned {:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/tim/MYprojects/randomex/_build/dev/lib/sfmt/priv/sfmt_nif.so, 2): image not found\''}}
```

And fail in runtime

```
        ** (UndefinedFunctionError) undefined function :sfmt.seed/3 (module :sfmt is not available)
            (sfmt) :sfmt.seed(1949341621, 311903054, 557531173)
```

Erlang 18.2.1
Elixir 1.2.0
MacOS 10.11.2

**Comment by jj1bdx** [comment]
@timCF Actual examples to test? (I mean GitHub or any other repository)

Note: HiPE or native compilation and NIF do not coexist.

**Comment by timCF** [comment]
@jj1bdx Example is here
https://github.com/timCF/randomex
I build erlang with disabled HiPE , but it not works yet

**Comment by timCF** [comment]
on linux also not works, the same errors

**Comment by jj1bdx** [comment]
@timCF 0.12.7 should solve the problem. I'm still experimenting on the general building issues with mix and hex, so feel free to make a suggestion.

**Comment by jj1bdx** [comment]
@timCF the reason of 0.12.2 errors was NIF shared library was not built at all.

**Comment by jj1bdx** [comment]
@timCF Can you confirm this issue has been fixed (especially with hex 0.12.0)?

**Comment by timCF** [comment]
@jj1bdx yes, it works! Thx!

**Comment by jj1bdx** [comment]
@timCF Very good. Issue closed.
