### ISSUE TITLE
Erroneous specs

### ISSUE THREAD

**Issue by kostis** [jj1bdx/sfmt-erlang#28]
The spec in the following line https://github.com/jj1bdx/sfmt-erlang/blob/master/src/sfmt.erl#L286 should read:

`-spec uint32_to_float(0..4294967295) -> float().`

A similar change should happen to the spec in the following line https://github.com/jj1bdx/sfmt-erlang/blob/master/src/sfmt_pure.erl#L574

**Comment by jj1bdx** [comment]
@kostis I'll fix them soon. Thx!

**Comment by jj1bdx** [comment]
Fixed as in https://github.com/jj1bdx/sfmt-erlang/commit/4e6eab7ab6d382219268f1f38a061b680be5bdba
Thx @kostis!
