### ISSUE TITLE
erl_nif.h: No such file or directory  #include "erl_nif.h"

### ISSUE THREAD

**Issue by crisefd** [jj1bdx/sfmt-erlang#29]
I'm writing a genetic algorithm in Elixir, I'm a newbie in the language. I have this error when installing the library, this is the deps in mi mix file
```
defp deps do
    [{:sfmt_erlang, git: "https://github.com/jj1bdx/sfmt-erlang.git"}]
  end
```
Then a I did `mix deps.get` and then `mix deps.compile` throws the error:
```
make[1]: Entering directory `/home/ubuntu/workspace/elixir_ga/deps/sfmt_erlang'
 C      sfmt_nif.c
/home/ubuntu/workspace/elixir_ga/deps/sfmt_erlang/c_src/sfmt_nif.c:53:21: fatal error: erl_nif.h: No such file or directory
 #include "erl_nif.h"
                     ^
compilation terminated.
```

**Comment by jj1bdx** [comment]
`erl_nif.h` is a part of OTP distribution. Check this out for the workaround. http://stackoverflow.com/questions/7132598/erl-nif-h-not-found

Note that my mix script might not handle the issue well. Use `make` if building with `mix` does not solve.

**Comment by jj1bdx** [comment]
Also if you're using Ubuntu's native package, be sure that erlang-dev is installed.

**Comment by jj1bdx** [comment]
One more advice: sfmt is already in the hex.pm package. See https://hex.pm/packages/sfmt

**Comment by crisefd** [comment]
Yeah, I did not have erlang-dev installed. Because I use Ubuntu I did

`sudo apt-get install erlang-dev`

Now it compiles well, thanks a lot

**Comment by jj1bdx** [comment]
@crisefd Glad to see you've sorted out the problem! :)
